#include "m_bg_tex.h"

u8 sprashC_tex_dummy[512];
u8 sprashA_tex_dummy[512];
u8 wave3_tex_dummy[1024];
u8 wave2_tex_dummy[2048];
u8 wave1_tex_dummy[1024];
u8 sand_tex_dummy[1024];
u8 beach_pal_dummy2[16 * sizeof(u16)];
u8 beach2_tex_dummy2[256];
u8 beach1_tex_dummy2[1024];
u8 beach_tex_dummy[2048];
u8 tunnel_tex_dummy[2048];
u8 rail_pal_dummy[16 * sizeof(u16)];
u8 bush_pal_dummy[16 * sizeof(u16)];
u8 cliff_pal_dummy[16 * sizeof(u16)];
u8 earth_pal_dummy[16 * sizeof(u16)];
u8 station_pal_dummy[16 * sizeof(u16)];
u8 bridge_2_pal_dummy[16 * sizeof(u16)];
u8 bridge_1_pal_dummy[16 * sizeof(u16)];
u8 tekkyo_tex_dummy[2048];
u8 bridge_2_tex_dummy[2048];
u8 bridge_1_tex_dummy[2048];
u8 water_2_tex_dummy[512];
u8 water_1_tex_dummy[512];
u8 river_tex_dummy[1024];
u8 stone_tex_dummy[2048];
u8 station_tex_dummy[2048];
u8 rail_tex_dummy[2048];
u8 grass_tex_dummy[512];
u8 bush_b_tex_dummy[1024];
u8 bush_a_tex_dummy[2048];
u8 cliff_tex_dummy[2048];
u8 earth_tex_dummy[2048];

BSS_ORDER_GROUP_START
  BSS_ORDER_ITEM(sprashC_tex_dummy);
  BSS_ORDER_ITEM(sprashA_tex_dummy);
  BSS_ORDER_ITEM(wave3_tex_dummy);
  BSS_ORDER_ITEM(wave2_tex_dummy);
  BSS_ORDER_ITEM(wave1_tex_dummy);
  BSS_ORDER_ITEM(sand_tex_dummy);
  BSS_ORDER_ITEM(beach_pal_dummy2);
  BSS_ORDER_ITEM(beach2_tex_dummy2);
  BSS_ORDER_ITEM(beach1_tex_dummy2);
  BSS_ORDER_ITEM(beach_tex_dummy);
  BSS_ORDER_ITEM(tunnel_tex_dummy);
  BSS_ORDER_ITEM(rail_pal_dummy);
  BSS_ORDER_ITEM(bush_pal_dummy);
  BSS_ORDER_ITEM(cliff_pal_dummy);
  BSS_ORDER_ITEM(earth_pal_dummy);
  BSS_ORDER_ITEM(station_pal_dummy);
  BSS_ORDER_ITEM(bridge_2_pal_dummy);
  BSS_ORDER_ITEM(bridge_1_pal_dummy);
  BSS_ORDER_ITEM(tekkyo_tex_dummy);
  BSS_ORDER_ITEM(bridge_2_tex_dummy);
  BSS_ORDER_ITEM(bridge_1_tex_dummy);
  BSS_ORDER_ITEM(water_2_tex_dummy);
  BSS_ORDER_ITEM(water_1_tex_dummy);
  BSS_ORDER_ITEM(river_tex_dummy);
  BSS_ORDER_ITEM(stone_tex_dummy);
  BSS_ORDER_ITEM(station_tex_dummy);
  BSS_ORDER_ITEM(rail_tex_dummy);
  BSS_ORDER_ITEM(grass_tex_dummy);
  BSS_ORDER_ITEM(bush_b_tex_dummy);
  BSS_ORDER_ITEM(bush_a_tex_dummy);
  BSS_ORDER_ITEM(cliff_tex_dummy);
  BSS_ORDER_ITEM(earth_tex_dummy);
BSS_ORDER_GROUP_END
